Modificaciones al README en español.
labexp/data_scripts_lascallesdelasmujeres pull request #2
Opened 2018-08-14 21:02 UTC by tammypmc

Completa el issue #1

2018-08-14 23:45 UTC, jamescr requested changes

2018-08-14 23:45 UTC, jamescr commented on README.md
> +npm run step3 -- --ciudad=nombreciudad
¿no me queda claro cuál es el cambio acá?

2018-08-14 23:45 UTC, jamescr commented on README.md
> +npm run step4 -- --ciudad=nombreciudad
¿no me queda claro cuál es el cambio acá?

2018-08-17 18:03 UTC, tammypmc commented on README.md
> +npm run step3 -- --ciudad=nombreciudad
El guión original venia en un formato que cuando se copiaba a la terminal se veía diferente a un guión normal y la terminal no reconocía el step por esta razon. Borrándolo y poniéndole un guión nuevo se arreglaba el problema.

2018-08-17 18:03 UTC, tammypmc commented on README.md
> +npm run step4 -- --ciudad=nombreciudad
El guión original venia en un formato que cuando se copiaba a la terminal se veía diferente a un guión normal y la terminal no reconocía el step por esta razon. Borrándolo y poniéndole un guión nuevo se arreglaba el problema.

2018-08-21 17:18 UTC, jamescr commented
Ok. Ya entiendo. Buenísimo. Quizás, para la próxima, sería bueno indicar el problema del guión en la descripción del PR.

2018-08-21 17:18 UTC, jamescr approved these changes

2018-09-20 19:18 UTC, merged